title: Hyunah Khoo
description: The online CV of Hyunah Khoo.
url: "https://hyunah1224.github.io"
theme: jekyll-theme-minimal

logo: /assets/img/logo_transparent.png
profile_picture: assets/img/toyobunko2.jpg
